name: Ultra Fast macOS Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Create minimal renderer
      run: |
        mkdir -p renderer/build
        echo '<!DOCTYPE html><html><head><title>Disparador MEH</title><style>body{font-family:Arial;text-align:center;padding:50px;background:#f0f0f0}div{background:white;padding:30px;border-radius:10px;box-shadow:0 5px 15px rgba(0,0,0,0.1)}h1{color:#333}</style></head><body><div><h1>🚀 Disparador MEH</h1><p>Sistema de Reconexão Automática Ativo</p><p>✅ ECONNRESET tratado</p><p>✅ ConnectionHelper ativo</p><p>✅ Configurações otimizadas</p></div></body></html>' > renderer/build/index.html
        
    - name: Install only essential dependencies
      run: |
        npm install --no-optional --no-audit --no-fund
        npm install -g electron-builder@latest
        
    - name: Build macOS app
      run: npm run build:mac
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DisparadorMEH-macOS
        path: dist/*.dmg
        retention-days: 30
        
    - name: Create release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.dmg
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          ## Disparador MEH - macOS Build (Ultra Fast)
          
          ### 🚀 Melhorias Implementadas:
          - ✅ **Sistema de reconexão automática**
          - ✅ **Tratamento robusto de erros ECONNRESET**
          - ✅ **ConnectionHelper para gerenciar conexões**
          - ✅ **Configurações centralizadas**
          - ✅ **Sistema de trial robusto**
          
          ### 📦 Arquivos incluídos:
          - `DisparadorMEH.dmg` - Instalador para macOS
          
          ### 🔧 Instalação:
          1. Baixe o arquivo .dmg
          2. Abra o arquivo
          3. Arraste o app para a pasta Applications
          4. Execute o aplicativo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
